// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhQM3ZrHYz34Y3FKmkPzWlazLOoPJIKKA',
    appId: '1:732661799079:web:8de7b1477c3a143e3c2382',
    messagingSenderId: '732661799079',
    projectId: 'com-cipherschools-assign-95bdb',
    authDomain: 'com-cipherschools-assign-95bdb.firebaseapp.com',
    storageBucket: 'com-cipherschools-assign-95bdb.firebasestorage.app',
    measurementId: 'G-BSDPLYPW8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3YfW_TpUDeEfBVc4YIhga131IcmGp_sQ',
    appId: '1:732661799079:android:98863c0c4babf9423c2382',
    messagingSenderId: '732661799079',
    projectId: 'com-cipherschools-assign-95bdb',
    storageBucket: 'com-cipherschools-assign-95bdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUz07f8bNVnLFtgVTir4Kj5QL00iQ09XI',
    appId: '1:732661799079:ios:779679511e81bbe13c2382',
    messagingSenderId: '732661799079',
    projectId: 'com-cipherschools-assign-95bdb',
    storageBucket: 'com-cipherschools-assign-95bdb.firebasestorage.app',
    iosClientId: '732661799079-2dc05cpv8bd2or8ctj0ua6ikjgeg498i.apps.googleusercontent.com',
    iosBundleId: 'com.example.cipherx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUz07f8bNVnLFtgVTir4Kj5QL00iQ09XI',
    appId: '1:732661799079:ios:779679511e81bbe13c2382',
    messagingSenderId: '732661799079',
    projectId: 'com-cipherschools-assign-95bdb',
    storageBucket: 'com-cipherschools-assign-95bdb.firebasestorage.app',
    iosClientId: '732661799079-2dc05cpv8bd2or8ctj0ua6ikjgeg498i.apps.googleusercontent.com',
    iosBundleId: 'com.example.cipherx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhQM3ZrHYz34Y3FKmkPzWlazLOoPJIKKA',
    appId: '1:732661799079:web:62503cd3f1ae97963c2382',
    messagingSenderId: '732661799079',
    projectId: 'com-cipherschools-assign-95bdb',
    authDomain: 'com-cipherschools-assign-95bdb.firebaseapp.com',
    storageBucket: 'com-cipherschools-assign-95bdb.firebasestorage.app',
    measurementId: 'G-HB0C9BN1RS',
  );
}
